[package]
name = "userspace_rust_loader"
version = "0.1.0"
authors = ["Simon Scannell <s.scannell@web.de>"]
edition = "2018"

[[bin]]
name = "loader"
path = "src/loader/main.rs"

[dependencies]
nix = "0.19.0"
libc = "0.2.80"
rand = "0.7"
